### ISSUE TITLE
Компоновка кода

### ISSUE THREAD

**Issue by alex-ks** [nikkollaii/MessageQueue#1]
В проекте 5 классов, и все они находятся в одном файле, это тяжеловато для восприятия. Несмотря на то, что шарпы позволяют слепить всё в один файл, лучше делать как в Java: один класс - один файл.

Кроме того, в чём необходимость размещать классы Message и Handler внутри класса MessageQueue?

**Comment by nikkollaii** [comment]
Разнёс по различным файлам. 
размещал классы Message и Handler внутри класса MessageQueue по привычки работы с java (там это даёт дополнительную видимость)
