### ISSUE TITLE
ForEach

### ISSUE THREAD

**Issue by alex-ks** [nikkollaii/MessageQueue#3]
Метод 

```C#
public void RegisterHandler (List<T> messages, Action<T> handler, bool reentrant = false)
{
	messages.ForEach(delegate (T message) {
		RegisterHandler(message, handler);
	});
}
```
вызывает несколько вопросов.

1. Почему был использован метод `List.ForEach` вместо языковой конструкции `foreach`?
2. Аргумент метода `List.ForEach` лучше сделать не в виде анонимного делегата, а в виде лямбда-выражения (это касается и других мест).
3. Аргумент reentrant никак не используется в функции.

**Comment by nikkollaii** [comment]
1. Предпочтений как таковых не было.
2. Исправлено
3. Исправлено
