### ISSUE TITLE
Потокобезопасность

### ISSUE THREAD

**Issue by alex-ks** [nikkollaii/MessageQueue#4]
Что в `MessageQueue` может пойти не так, если:
1. Одновременно вызвать `RegisterHandler` из разных потоков?
2. Одновременно вызвать `RegisterHandler` и `Enqueue` из разных потоков?

Ожидалось ли такое использование класса?

**Comment by nikkollaii** [comment]
Не ожидалось

**Comment by nikkollaii** [comment]
Нужно ли реализовать?

**Comment by alex-ks** [comment]
Нет, не нужно.
