### ISSUE TITLE
Вызов делегатов

### ISSUE THREAD

**Issue by alex-ks** [nikkollaii/MessageQueue#5]
Вместо 
```C#
handler.Invoke(mes.message);
```
можно сделать просто 
```C#
handler(mes.message);
```
Также строку
```C#
message.setResultObj(asyncHandler.BeginInvoke(message, new AsyncCallback(AsyncCompleted), null));
```
можно заменить на 
```C#
message.setResultObj(asyncHandler.BeginInvoke(message, AsyncCompleted, null));
```
Если интересно, можно проверить, создаётся ли в каком-либо из случаев новый объект на куче.

**Comment by nikkollaii** [comment]
Исправил

**Comment by alex-ks** [comment]
Если существование метода

```C#
public Exception Exception()
{
    return exception;
}
```
нужно только для публичного доступа к исключению, то лучше просто на get и set навесить разные модификаторы доступа.
